### ISSUE TITLE
(Not an issue) New Teams API

### ISSUE THREAD

**Issue by AntoineGS** [lafe/Teams2Mqtt#2]
I have a similar app up for the new Teams and I documented the API/JSON calls for it if you want to add support in your application! https://github.com/AntoineGS/teams-status-rs

**Comment by lafe** [comment]
Thank you very much for that! The development branch already has a version with support for the new Teams version, but I have to clean it up and write the documentation. My findings are very similar to yours. It's a pity that there is no official documentation from Microsoft...

**Comment by ghost** [comment]
So one  year later, are you able to integrate it?
